services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./bookie.sql:/docker-entrypoint-initdb.d/create_script.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
      - PGDATA=/var/lib/postgresql/data/ <--- Check this out
